dist: trusty
sudo: required
language: java
jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master
    - /support\/.*/
    - fix/search-1915-keystore-metadata

install: travis_retry mvn install -DskipTests=true -B -V

stages:
  - test
  - release

jobs:
  include:
    - stage: test
      name: "Build and test"
      script: travis_retry mvn test
    - name: "WhiteSource scan"
      # only on SP branches or master and if it is not a PR
      if: fork = false AND (branch = master OR branch =~ /support\/SP\/.*/) AND type != pull_request
      script:
        # Download the latest version of WhiteSource Unified Agent
        - curl -LJO https://github.com/whitesource/unified-agent-distribution/raw/master/standAlone/wss-unified-agent.jar
        # Run WhiteSource Unified Agent
        - java -jar wss-unified-agent.jar -apiKey ${WHITESOURCE_API_KEY} -c .wss-unified-agent.config
    - name: "Source Clear Scan"
      # only on SP branches or master and if it is not a PR
      if: fork = false AND (branch = master OR branch =~ /support\/SP\/.*/) AND type != pull_request
      script: skip
      addons:
        srcclr: true
    - stage: release
      name: "Push to Nexus"
      if: fork = false AND (branch = fix/search-1915-keystore-metadata) AND type != pull_request AND commit_message !~ /\[no-release\]/
      before_install:
        - "cp .travis.settings.xml $HOME/.m2/settings.xml"
      script:
        # Use full history for release
        - git checkout -B "${TRAVIS_BRANCH}"
        # Add email to link commits to user
        - git config user.email "${GIT_EMAIL}"
        # Skip building of release commits
        - mvn --batch-mode -q -DscmCommentPrefix="[maven-release-plugin][skip ci] " -Dusername="${GIT_USERNAME}" -Dpassword="${GIT_PASSWORD}" -DskipTests -Darguments=-DskipTests -DreleaseVersion=search-1915-6 -DdevelopmentVersion=8.28-SNAPSHOT release:clean release:prepare release:perform
