dist: trusty
sudo: required
language: java
jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

install: travis_retry mvn install -DskipTests=true -B -V

matrix:
  include:
    - name: "Build and test"
      script: travis_retry mvn test
    - name: "WhiteSource scan"
      if: fork = false AND branch = master
      script:
        # Download the latest version of WhiteSource FS Agent
        - curl -LJO https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/whitesource-fs-agent.jar
        # Run WhiteSource FS Agent
        - java -jar whitesource-fs-agent.jar -apiKey ${WHITESOURCE_API_KEY} -c .whitesource-fs-agent.config